name: Test
on:
  push:
    branches: [main]
    paths:
      - "*.sh"
      - denow
      - denow.bat
      - .github/workflows/test.yml
  pull_request:
    branches: [main]
    paths:
      - "*.sh"
      - denow
      - denow.bat
      - .github/workflows/test.yml
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      # Doesn't work on Windows
      - if: runner.os != 'Windows'
        uses: ludeeus/action-shellcheck@master
      - if: runner.os != 'Windows'
        run: ./deno_wrapper.test.sh
      - if: runner.os == 'Windows'
        run: ./deno_wrapper.test.bat
