name: Test
on:
  push:
    branches: [main]
    paths:
      - "*.sh"
      - "*.ps1"
      - .github/workflows/test.yml
  pull_request:
    branches: [main]
    paths:
      - "*.sh"
      - "*.ps1"
      - .github/workflows/test.yml
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ludeeus/action-shellcheck@master
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: ./install.test.sh
  # test-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: ./install.test.ps1
